name: UsefulCMDs
main: com.nicka101.UsefulCMDs.UsefulCMDs
version: 1.9.5c
description: >
             A Collection of Useful Commands for Server Admins
commands:
  diff:
    description: Displays or Changes the Difficulty for the Current World
    usage: /diff [easy|e|normal|n|hard|h|peaceful|p]
    permission: usefulcmds.difficulty
    permission-message: You don't have the Required Permission to perform this Command.
  difficulty:
    description: Displays or Changes the Difficulty for the Current World
    usage: /difficulty [easy|e|normal|n|hard|h|peaceful|p]
    permission: usefulcmds.difficulty
    permission-message: You don't have the Required Permission to perform this Command.
  pvp:
    description: Toggles PvP flag for the Current World
    usage: /pvp
    permission: usefulcmds.pvp
    permission-message: You don't have the Required Permission to perform this Command.
  shoot:
    description: Shoots an Arrow
    usage: /shoot
    permission: usefulcmds.shoot
    permission-message: You don't have the Required Permission to perform this Command.
  thunder:
    description: Starts a 1000 tick long Thunder Storm in the current world
    usage: /thunder
    permission: usefulcmds.thunder
    permission-message: You don't have the Required Permission to perform this Command.
  target:
    description: Makes all hostile mobs target the specified player.
    usage: /target <player>
    permission: usefulcmds.target
    permission-message: You don't have the Required Permission to perform this Command.
  mount:
    description: Allows you to ride other players
    usage: /mount <player_to_ride> [passenger default=you]
    permission: usefulcmds.mount
    permission-message: You don't have the Required Permission to perform this Command.
  spawncj:
    description: Spawns a Creeper Jockey at your current position or at the position of another player.
    usage: /spawncj [player default=you]
    permission: usefulcmds.spawncj
    permission-message: You don't have the Required Permission to perform this Command.
  effect:
    description: Adds Potion Effects to a player.
    usage: /effect <blind|nodmg|jump|confuse|dig|fire_res|hunger|strength|regen|poison|slowness|speed|water|weakness> <duration= short|medium|long> <player>
    permission: usefulcmds.effects
    permission-message: You don't have the Required Permission to perform this Command.
  death:
    description: Plays the Death Animation for a Player.
    usage: /death [player]
    permission: usefulcmds.death
    permission-message: You don't have the Required Permission to perform this Command.
  hidefrom:
    description: Prevent the specified player from seeing you.
    usage: /hidefrom
    permission: usefulcmds.hide
    permission-message: You don't have the Required Permission to perform this Command.
  freeze:
    description: Freezes a Player in Place.
    usage: /freeze <player>
    permission: usefulcmds.freeze
    permission-message: You don't have the Required Permission to perform this Command.
  buildanything:
    description: Enables you to build without restriction from standard MC rules.
    usage: /buildanything
    permission: usefulcmds.buildanything
    permission-message: You don't have the Required Permission to perform this Command.
  launchmobs:
    description: Launches All Mobs into the air.
    usage: /launchmobs
    permission: usefulcmds.launchmobs
    permission-message: You don't have the Required Permission to perform this Command.
  launchplayer:
    description: Launches the specified player on an Arrow.
    usage: /launchplayer [player]
    permission: usefulcmds.launchplayer
    permission-message: You don't have the Required Permission to perform this Command.
  bed:
    description: Sets Your Bed Spawn to the current Location.
    usage: /bed [unset]
    permission: usefulcmds.bed
    permission-message: You don't have the Required Permission to perform this Command.
  invedit:
    description: Allows You To Edit Another Player's Inventory.
    usage: /invedit <player>
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  craft:
    description: Opens The Crafting Menu Regardless of Where You Are.
    usage: /craft
    permission: usefulcmds.craft
    permission-message: You don't have the Required Permission to perform this Command.
  enchanting:
    description: Opens The Enchanting Menu Regardless of Where You Are.
    usage: /enchanting
    permission: usefulcmds.enchanting
    permission-message: You don't have the Required Permission to perform this Command.
  dmount:
    description: Allows you to ride other players
    usage: /dmount <player_to_ride>
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  nunstuck:
    description: Gets You Out Of The Roof Of The Nether When Stuck There
    usage: /nunstuck
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  console:
    description: Runs a Command as Console
    usage: /console <command>
    permission: usefulcmds.console
    permission-message: You don't have the Required Permission to perform this Command.
  usefulcmds:
    description: Displays Version Information
    usage: /usefulcmds
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  powerup:
    description: Sets All Creepers To Powered
    usage: /powerup
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  mobstream:
    description: Streams All Mobs
    usage: /mobstream
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  nopickup:
    description: Disables Block Pickup
    usage: /nopickup
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  playerinfo:
    description: Displays Information About the Specified Player
    usage: /playerinfo <player>
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  specialplace:
    description: Does Nothing
    usage: /specialplace
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  chworld:
    description: Teleports You or the Specified Player to the Specified World.
    usage: /chworld <world name> [player]
    permission: usefulcmds.chworld
    permission-message: You don't have the Required Permission to perform this Command.
  chworldf:
    description: Teleports You or the Specified Player to the Specified World (Force Creation if Not Found. Force Open if Not In Bukkit.yml).
    usage: /chworldf <world name> [player]
    permission: usefulcmds.chworldf
    permission-message: You don't have the Required Permission to perform this Command.
  ijail:
    description: Pretends To Trap The Specified Player
    usage: /ijail <playername>
    permission: usefulcmds.ijail
    permission-message: You don't have the Required Permission to perform this Command.
  fly:
    description: Allow Yourself To Fly
    usage: /fly
    permission: usefulcmds.fly
    permission-message: You don't have the Required Permission to perform this Command.
  test:
    description: Allow Yourself To Fly
    usage: /test
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  armourequip:
    description: Equip Armour
    usage: /armourequip [player]
    permission:
    permission-message: You don't have the Required Permission to perform this Command.
  suicidal:
    description: Kill Yourself In Creative Ways
    usage: /suicidal
    permission: usefulcmds.suicide
    permission-message: You don't have the Required Permission to perform this Command.
  delayrun:
    description: Delay The Run Of A Command
    usage: /delayrun <time to wait (seconds)> <sender. console for console> <command>
    permission: usefulcmds.delayrun
    permission-message: You don't have the Required Permission to perform this Command.